name: Test Java API
run-name: ${{ github.actor }}, lets hope this works!

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "23"
      - name: "Gradle build"
        run: |
          cd api
          ./gradlew build
      - name: "Gradle test"
        run: |
          cd api
          ./gradlew test
      - name: "Send Success Email"
        run: |
          curl -X POST https://plunk.bobman.dev/api/v1/send
            -H 'Content-Type: application/json'
            -H 'Authorization: Bearer ${{ secrets.PLUNK_API_KEY }}'
            -d '{"email": "${{ github.event.commits[0].author.email }}", "body": "API test passed", "subject":"Well Done!"}'
          echo "Send email to ${github.event.commits[0].author.email}"
